water heater working
hes-pnnl/hes-rest pull request #6
Opened 2022-11-30 19:15 UTC by RaeChen07

2022-12-02 17:46 UTC, thepriestscottage requested changes

2022-12-02 17:46 UTC, thepriestscottage commented on src/Models/ReplaceWhFuelWithNg.ts
> +                        upgrade_values: [+flat_object.value]
Same as previous

2022-12-02 17:46 UTC, thepriestscottage commented on src/Models/ReplaceWhWithHeatPump.ts
> +            for (let flat_object of flat_lu_havc_effciency_upgrade){
Since the code is most of these files is similar, I will say my previous comments on naming/parsing apply throughout

2022-12-02 19:45 UTC, RaeChen07 commented on src/Datas/lu_water_heater_efficiency.csv
> +year,performance_id,type_id,fuel_primary_id,metric_id,units_id,value
I don't think they are changing, also for the heating eff lu, they have the same headers

2022-12-06 16:59 UTC, thepriestscottage approved these changes
Pending whether we add types for the lu_* objects, I think this is good

2022-12-07 01:40 UTC, merged